# Generated by Django 4.1.7 on 2023-04-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindOfAnimal', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Види тварин',
                'ordering': ['kindOfAnimal'],
            },
        ),
        migrations.CreateModel(
            name='BreedOfAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.animal')),
            ],
            options={
                'verbose_name': 'Породи тварин',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Клієнти',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[(None, 'Оберіть стать вашої тваринки'), ('a', 'Чоловічий'), ('b', 'Жіночий')], max_length=20)),
                ('breedOfAnimal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.breedofanimal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.client')),
            ],
            options={
                'verbose_name': 'Тваринки клієнтів',
                'ordering': ['nickname'],
            },
        ),
    ]
