# Generated by Django 4.1.7 on 2023-04-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofAdmission', models.DateTimeField()),
                ('statusTimetable', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.client')),
            ],
        ),
    ]
