# Generated by Django 4.1.7 on 2023-04-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_timetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['dateofAdmission'], 'verbose_name': 'Розклад прийомів'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='statusTimetable',
            field=models.BooleanField(blank=True),
        ),
    ]
