# Generated by Django 4.1.7 on 2023-05-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_client_email_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='kindOfAnimal',
            field=models.CharField(error_messages={'blank': 'Укажіть тип тваринки'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='breedofanimal',
            name='name',
            field=models.CharField(error_messages={'blank': 'Укажіть породу тваринки'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(error_messages={'blank': "Введіть значення до поля 'Електрона почта клієнта'"}, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(error_messages={'blank': "Введіть значення до поля 'Ім'я клієнта'"}, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(error_messages={'blank': "Введіть значення до поля 'Прізвище клієнта'"}, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(error_messages={'blank': "Введіть значення до поля 'Номер мобільного телефону клієнта'", 'max_length': 'Введено багато символів. Номер телефону має містити 13 символів'}, max_length=13),
        ),
        migrations.AlterField(
            model_name='clientpet',
            name='age',
            field=models.IntegerField(error_messages={'blank': 'Укажіть вік тваринки'}),
        ),
        migrations.AlterField(
            model_name='clientpet',
            name='nickname',
            field=models.CharField(error_messages={'blank': 'Введіть значення до поля Кличка'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clientpet',
            name='sex',
            field=models.CharField(choices=[(None, 'Оберіть стать вашої тваринки'), ('a', 'Чоловічий'), ('b', 'Жіночий')], error_messages={'blank': 'Укажіть стать тваринки'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='dateofAdmission',
            field=models.DateField(error_messages={'blank': 'Укажіть дату прийому'}),
        ),
    ]
